AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: The environment name. Used to distinguish resources in multiple environments.

Resources:
  ClippingsAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: ClippingsAPI
      EndpointConfiguration:
        Type: REGIONAL
      StageName: dev
  ClippingsDispatcher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dispatcher/
      Handler: dispatcher
      Runtime: go1.x
      Environment:
        Variables:
          ClippingsTableName:
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /clippings
            Method: POST
            RestApiId: !Ref ClippingsAPI
  ClippingsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      # ProvisionedThroughput: Not specified, then on-demand mode.
      TableName:
        !Join
          - '-'
          - - !Ref Environment
            - Clippings

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ClippingsDispatcherFunction:
    Value: !GetAtt ClippingsDispatcher.Arn
